name: Build Preview

on:
  pull_request:
    branches: [main]

jobs:
  build_ios_dev:
    name: Build iOS (Development)
    type: build
    params:
      platform: ios
      profile: development

  build_android_dev:
    name: Build Android (Development)
    type: build
    params:
      platform: android
      profile: development
